# Auto-generated by qt-pods.
# This file should be put under version control.
TEMPLATE = subdirs
SUBDIRS = bindings \
            holosqape \
            holoconsole
holosqape.depends = bindings
holoconsole.depends = bindings
CONFIG += debug_and_release
