# Auto-generated by qt-pods.
# This file should be put under version control.
TEMPLATE = subdirs
SUBDIRS = bindings \
            holosqape \
            holotests
holosqape.depends = bindings
holotests.depends = bindings
include(pods-subdirs.pri)
